\documentclass [a4paper]{article}
\title{Mini-Projet}
\author{GUO Lieqiang}
\begin{document}
\SweaveOpts{concordance=TRUE,echo= TRUE}
\maketitle
In this example we embed parts of the examples from the
\texttt {kruskal.test} help page into a \LaTeX{}document:
<<a>>=
data(airquality , package ="datasets")
library ("stats")
kruskal.test(Ozone ~ Month , data = airquality)
1+4
@
which shows that the location parameter of the Ozone
distribution varies significantly from month to month . Finally we
include a boxplot of the data :
@

<<b>>=
<<a>>
  
@

\begin{center}
<<fig = TRUE , echo = True>>=
library("graphics")
1+2
a <- 5/100;
n <- c(10, 100, 1000);
quantille <- 1-a/2;
A_n <- qnorm(quantille)/sqrt(n);
t(matrix(c(n,A_n),3))
u <- 0.1;
n0 <- 0;
R_H1 <- c();
beta <- 0.95;
n <- seq(50,5000,200);
A_n <- qnorm(quantille)/sqrt(n)
for (i in n){
  temp_R_H1 <- pnorm(q = A_n[which(i==n)], mean = u, sd = sqrt(1/i)) - pnorm(q = - A_n[which(i==n)], mean = u, sd = sqrt(1/i))
  R_H1 <- c(R_H1, temp_R_H1)
}
n0 <- n[min(which((1 - R_H1) >= beta))]
n0
plot(n, R_H1, type = 'l')

n <- seq(50,n0,1)
A_n <- qnorm(quantille)/sqrt(n)
R_H1 <- c()
for (i in n){
  temp_R_H1 <- pnorm(q = A_n[which(i==n)], mean = u, sd = sqrt(1/i)) - pnorm(q = - A_n[which(i==n)], mean = u, sd = sqrt(1/i))
  R_H1 <- c(R_H1, temp_R_H1)
}
n0 <- n[min(which((1 - R_H1) >= beta))]
n0
boxplot( Ozone ~ Month , data = airquality )
@

\end{center}
\begin{center}
<<fig = TRUE , echo = FALSE>>=
plot(1:10,11:20)
@
\end{center}
\end{document}